changelog:
  categories:
    - title: "Breaking changes"
      labels:
        - breaking-change

    - title: "What’s new"
      labels:
        - feature

    - title: "Enhancements"
      labels:
        - change

    - title: "Fixes"
      labels:
        - bug

  exclude:
    labels:
      - skip-changelog