name: Publish Development Build

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.details.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Extract build details
        id: details
        run: echo "version=${GITHUB_REF##*/}-${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

  publish:
    needs: prepare
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Build and publish project
        uses: ./.github/actions/gradle-build
        env:
          PUBLISH_USER: ${{ secrets.PUBLISH_USER }}
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
          VERSION: ${{ needs.prepare.outputs.version }}
          PUBLISH_REALM: development
        with:
          gradle-command: ./gradlew --no-daemon test publish
